#
# logging
#
logging:
  level:
    root: info
    com.memorynotfound: info
    org.springframework.web: info
    org.springframework.security: info
    org.hibernate.SQL: debug
#
# JDBC connection properties
#
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/sfg_dev?useSSL=false&serverTimezone=UTC&useUnicode=true&useJDBCCompliantTimezoneShift=true;
#    username: er_dev_user
#    password: pas1
#    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    hikari:
      data-source-properties:
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
#
# MultipartProperties
#
# Enable multipart uploads
  servlet:
    multipart:
      enabled: true
      # Threshold after which files are written to disk.
      file-size-threshold: 2KB
      # Max file size.
      max-file-size: 30MB
      # Max Request Size
      max-request-size: 30MB


#  main:

    # The Open Session In View Anti-Pattern
#    open-in-view: false
#    allow-bean-definition-overriding: true

#  resources:
#    static-locations: /kowboj3f/src/main/webapp/WEB-INF/views/jsp/

#
# Initial schema generation - first startup
#
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: easyrider_database_create.sql

#
# Connection pool properties
#
#connection:
#  pool:
#    initialPoolSize: 5
#    minPoolSize: 5
#    maxPoolSize: 20
#    maxIdleTime: 3000




